"use client";

import type { ExtendedEmployee, ActivityLog } from "./types";

export const FALLBACK_TEAM: ExtendedEmployee[] = [
  {
    id: "1",
    name: "Alexey Petrov",
    email: "a.petrov@vendhub.uz",
    phone: "+998 90 123 45 67",
    avatar: "AP",
    role: "owner",
    department: "management",
    position: "Director",
    status: "active",
    lastActive: "2 min ago",
    joinedAt: "2024-01-15",
    tasksCompleted: 156,
    rating: 4.9,
    telegramId: "@alexey_petrov",
    sessions: 3,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Aziz Karimov",
    email: "a.karimov@vendhub.uz",
    phone: "+998 91 234 56 78",
    avatar: "AK",
    role: "admin",
    department: "management",
    position: "System Administrator",
    status: "active",
    lastActive: "5 min ago",
    joinedAt: "2024-03-01",
    tasksCompleted: 234,
    rating: 4.8,
    telegramId: "@aziz_karimov",
    sessions: 2,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01",
  },
  {
    id: "3",
    name: "Malika Rakhimova",
    email: "m.rahimova@vendhub.uz",
    phone: "+998 93 345 67 89",
    avatar: "MR",
    role: "manager",
    department: "operations",
    position: "Operations Manager",
    status: "active",
    lastActive: "15 min ago",
    joinedAt: "2024-02-10",
    tasksCompleted: 189,
    rating: 4.7,
    telegramId: "@malika_r",
    sessions: 1,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
  },
  {
    id: "4",
    name: "Dmitry Kozlov",
    email: "d.kozlov@vendhub.uz",
    phone: "+998 94 456 78 90",
    avatar: "DK",
    role: "operator",
    department: "service",
    position: "Technician",
    status: "active",
    lastActive: "1 hour ago",
    joinedAt: "2024-04-15",
    tasksCompleted: 312,
    rating: 4.5,
    telegramId: "@dmitry_k",
    sessions: 1,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-04-15",
    updatedAt: "2024-04-15",
  },
  {
    id: "5",
    name: "Nodira Khasanova",
    email: "n.hasanova@vendhub.uz",
    phone: "+998 95 567 89 01",
    avatar: "NK",
    role: "warehouse",
    department: "operations",
    position: "Warehouse Manager",
    status: "active",
    lastActive: "30 min ago",
    joinedAt: "2024-05-20",
    tasksCompleted: 98,
    rating: 4.6,
    telegramId: "@nodira_h",
    sessions: 0,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-05-20",
    updatedAt: "2024-05-20",
  },
  {
    id: "6",
    name: "Elena Sidorova",
    email: "e.sidorova@vendhub.uz",
    phone: "+998 97 678 90 12",
    avatar: "ES",
    role: "accountant",
    department: "finance",
    position: "Chief Accountant",
    status: "active",
    lastActive: "2 hours ago",
    joinedAt: "2024-06-01",
    tasksCompleted: 67,
    rating: 4.4,
    sessions: 1,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-06-01",
    updatedAt: "2024-06-01",
  },
  {
    id: "7",
    name: "Sergey Novikov",
    email: "s.novikov@vendhub.uz",
    phone: "+998 90 789 01 23",
    avatar: "SN",
    role: "operator",
    department: "service",
    position: "Service Engineer",
    status: "away",
    lastActive: "4 hours ago",
    joinedAt: "2024-07-10",
    tasksCompleted: 145,
    rating: 4.3,
    telegramId: "@sergey_n",
    sessions: 0,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-07-10",
    updatedAt: "2024-07-10",
  },
  {
    id: "8",
    name: "Alisher Usmanov",
    email: "a.usmanov@vendhub.uz",
    phone: "+998 91 890 12 34",
    avatar: "AU",
    role: "operator",
    department: "service",
    position: "Operator",
    status: "inactive",
    lastActive: "2 days ago",
    joinedAt: "2024-08-01",
    tasksCompleted: 87,
    rating: 4.2,
    sessions: 0,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-08-01",
    updatedAt: "2024-08-01",
  },
];

export const FALLBACK_ACTIVITY: ActivityLog[] = [
  {
    id: 1,
    userId: 2,
    userName: "Aziz Karimov",
    action: "create",
    target: "Sergey Novikov",
    details: "Employee added",
    timestamp: "10 min ago",
  },
  {
    id: 2,
    userId: 1,
    userName: "Alexey Petrov",
    action: "role_change",
    target: "Malika Rakhimova",
    details: "Role: operator -> manager",
    timestamp: "2 hours ago",
  },
  {
    id: 3,
    userId: 3,
    userName: "Malika Rakhimova",
    action: "edit",
    target: "Dmitry Kozlov",
    details: "Updated phone and department",
    timestamp: "5 hours ago",
  },
  {
    id: 4,
    userId: 1,
    userName: "Alexey Petrov",
    action: "delete",
    target: "Ivan Fyodorov",
    details: "Deleted inactive account",
    timestamp: "1 day ago",
  },
  {
    id: 5,
    userId: 2,
    userName: "Aziz Karimov",
    action: "login",
    target: "System",
    details: "Login from new device (iPhone 15)",
    timestamp: "1 day ago",
  },
];
