"use client";

import type { ExtendedEmployee, ActivityLog } from "./types";

export const FALLBACK_TEAM: ExtendedEmployee[] = [
  {
    id: "1",
    name: "Алексей Петров",
    email: "a.petrov@vendhub.uz",
    phone: "+998 90 123 45 67",
    avatar: "АП",
    role: "owner",
    department: "management",
    position: "Директор",
    status: "active",
    lastActive: "2 мин назад",
    joinedAt: "2024-01-15",
    tasksCompleted: 156,
    rating: 4.9,
    telegramId: "@alexey_petrov",
    sessions: 3,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Азиз Каримов",
    email: "a.karimov@vendhub.uz",
    phone: "+998 91 234 56 78",
    avatar: "АК",
    role: "admin",
    department: "management",
    position: "Системный администратор",
    status: "active",
    lastActive: "5 мин назад",
    joinedAt: "2024-03-01",
    tasksCompleted: 234,
    rating: 4.8,
    telegramId: "@aziz_karimov",
    sessions: 2,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01",
  },
  {
    id: "3",
    name: "Малика Рахимова",
    email: "m.rahimova@vendhub.uz",
    phone: "+998 93 345 67 89",
    avatar: "МР",
    role: "manager",
    department: "operations",
    position: "Менеджер операций",
    status: "active",
    lastActive: "15 мин назад",
    joinedAt: "2024-02-10",
    tasksCompleted: 189,
    rating: 4.7,
    telegramId: "@malika_r",
    sessions: 1,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
  },
  {
    id: "4",
    name: "Дмитрий Козлов",
    email: "d.kozlov@vendhub.uz",
    phone: "+998 94 456 78 90",
    avatar: "ДК",
    role: "operator",
    department: "service",
    position: "Техник",
    status: "active",
    lastActive: "1 час назад",
    joinedAt: "2024-04-15",
    tasksCompleted: 312,
    rating: 4.5,
    telegramId: "@dmitry_k",
    sessions: 1,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-04-15",
    updatedAt: "2024-04-15",
  },
  {
    id: "5",
    name: "Нодира Хасанова",
    email: "n.hasanova@vendhub.uz",
    phone: "+998 95 567 89 01",
    avatar: "НХ",
    role: "warehouse",
    department: "operations",
    position: "Складской менеджер",
    status: "active",
    lastActive: "30 мин назад",
    joinedAt: "2024-05-20",
    tasksCompleted: 98,
    rating: 4.6,
    telegramId: "@nodira_h",
    sessions: 0,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-05-20",
    updatedAt: "2024-05-20",
  },
  {
    id: "6",
    name: "Елена Сидорова",
    email: "e.sidorova@vendhub.uz",
    phone: "+998 97 678 90 12",
    avatar: "ЕС",
    role: "accountant",
    department: "finance",
    position: "Главный бухгалтер",
    status: "active",
    lastActive: "2 часа назад",
    joinedAt: "2024-06-01",
    tasksCompleted: 67,
    rating: 4.4,
    sessions: 1,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-06-01",
    updatedAt: "2024-06-01",
  },
  {
    id: "7",
    name: "Сергей Новиков",
    email: "s.novikov@vendhub.uz",
    phone: "+998 90 789 01 23",
    avatar: "СН",
    role: "operator",
    department: "service",
    position: "Сервис-инженер",
    status: "away",
    lastActive: "4 часа назад",
    joinedAt: "2024-07-10",
    tasksCompleted: 145,
    rating: 4.3,
    telegramId: "@sergey_n",
    sessions: 0,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-07-10",
    updatedAt: "2024-07-10",
  },
  {
    id: "8",
    name: "Алишер Усманов",
    email: "a.usmanov@vendhub.uz",
    phone: "+998 91 890 12 34",
    avatar: "АУ",
    role: "operator",
    department: "service",
    position: "Оператор",
    status: "inactive",
    lastActive: "2 дня назад",
    joinedAt: "2024-08-01",
    tasksCompleted: 87,
    rating: 4.2,
    sessions: 0,
    organizationId: "1",
    avatarUrl: null,
    createdAt: "2024-08-01",
    updatedAt: "2024-08-01",
  },
];

export const FALLBACK_ACTIVITY: ActivityLog[] = [
  {
    id: 1,
    userId: 2,
    userName: "Азиз Каримов",
    action: "create",
    target: "Сергей Новиков",
    details: "Добавлен сотрудник",
    timestamp: "10 мин назад",
  },
  {
    id: 2,
    userId: 1,
    userName: "Алексей Петров",
    action: "role_change",
    target: "Малика Рахимова",
    details: "Роль: оператор → менеджер",
    timestamp: "2 часа назад",
  },
  {
    id: 3,
    userId: 3,
    userName: "Малика Рахимова",
    action: "edit",
    target: "Дмитрий Козлов",
    details: "Обновлён телефон и отдел",
    timestamp: "5 часов назад",
  },
  {
    id: 4,
    userId: 1,
    userName: "Алексей Петров",
    action: "delete",
    target: "Иван Фёдоров",
    details: "Удалён неактивный аккаунт",
    timestamp: "1 день назад",
  },
  {
    id: 5,
    userId: 2,
    userName: "Азиз Каримов",
    action: "login",
    target: "Система",
    details: "Вход с нового устройства (iPhone 15)",
    timestamp: "1 день назад",
  },
];
