/**
 * COGS (Cost of Goods Sold) Event Listener
 *
 * Listens for 'sale.cogs.calculated' events emitted by deductIngredients()
 * and automatically creates a linked EXPENSE transaction recording
 * the cost of goods sold for each sale.
 *
 * Flow:
 *   Sale Transaction (COMPLETED)
 *     → deductIngredients() creates SaleIngredient records
 *     → emits 'sale.cogs.calculated' { transactionId, organizationId, totalCost }
 *     → THIS LISTENER creates Transaction(type=EXPENSE, expenseCategory=COGS)
 *       linked back to the original sale via metadata.sourceTransactionId
 */

import { Injectable, Logger } from "@nestjs/common";
import { OnEvent } from "@nestjs/event-emitter";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import {
  Transaction,
  TransactionType,
  TransactionStatus,
  ExpenseCategory,
} from "../entities/transaction.entity";

interface CogsCalculatedEvent {
  transactionId: string;
  organizationId: string;
  totalCost: number;
  ingredientCount: number;
}

@Injectable()
export class CogsListener {
  private readonly logger = new Logger(CogsListener.name);

  constructor(
    @InjectRepository(Transaction)
    private readonly transactionRepo: Repository<Transaction>,
  ) {}

  @OnEvent("sale.cogs.calculated")
  async handleCogsCalculated(event: CogsCalculatedEvent): Promise<void> {
    const { transactionId, organizationId, totalCost, ingredientCount } = event;

    if (totalCost <= 0) {
      this.logger.debug(
        `Skipping COGS expense for transaction ${transactionId}: totalCost=${totalCost}`,
      );
      return;
    }

    try {
      // Fetch the original sale transaction to copy machineId and date
      const saleTransaction = await this.transactionRepo.findOne({
        where: { id: transactionId },
        select: ["id", "machineId", "transactionDate", "saleDate"],
      });

      if (!saleTransaction) {
        this.logger.warn(
          `Sale transaction ${transactionId} not found for COGS expense creation`,
        );
        return;
      }

      // Check: don't create duplicate COGS expense for same sale
      const existing = await this.transactionRepo.findOne({
        where: {
          organizationId,
          type: TransactionType.EXPENSE,
          expenseCategory: ExpenseCategory.COGS,
        },
        // Use metadata to find the linked sale — raw query for jsonb
      });

      // More precise duplicate check via metadata
      if (existing) {
        const duplicateCheck = await this.transactionRepo
          .createQueryBuilder("t")
          .where("t.organizationId = :organizationId", { organizationId })
          .andWhere("t.type = :type", { type: TransactionType.EXPENSE })
          .andWhere("t.expenseCategory = :category", {
            category: ExpenseCategory.COGS,
          })
          .andWhere("t.metadata->>'sourceTransactionId' = :txnId", {
            txnId: transactionId,
          })
          .andWhere("t.deletedAt IS NULL")
          .getOne();

        if (duplicateCheck) {
          this.logger.debug(
            `COGS expense already exists for transaction ${transactionId}`,
          );
          return;
        }
      }

      // Create EXPENSE transaction for COGS
      const cogsExpense = this.transactionRepo.create({
        organizationId,
        machineId: saleTransaction.machineId,
        type: TransactionType.EXPENSE,
        status: TransactionStatus.COMPLETED,
        expenseCategory: ExpenseCategory.COGS,
        amount: totalCost,
        totalAmount: totalCost,
        currency: "UZS",
        transactionDate: saleTransaction.transactionDate,
        saleDate: saleTransaction.saleDate,
        description: `Себестоимость продажи (${ingredientCount} ингредиентов)`,
        metadata: {
          sourceTransactionId: transactionId,
          ingredientCount,
          autoGenerated: true,
          generatedAt: new Date().toISOString(),
        },
      });

      await this.transactionRepo.save(cogsExpense);

      this.logger.log(
        `COGS expense created: ${cogsExpense.id} for sale ${transactionId}, ` +
          `amount=${totalCost} UZS (${ingredientCount} ingredients)`,
      );
    } catch (error) {
      this.logger.error(
        `Failed to create COGS expense for transaction ${transactionId}: ` +
          `${error instanceof Error ? error.message : error}`,
      );
    }
  }
}
